version = 3.9.9
runner.dialect = scala3
maxColumn = 80
align.preset = none
align.stripMargin = false
newlines.source = keep
docstrings.style = SpaceAsterisk
docstrings.wrap = yes
docstrings.oneline = keep
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = false
